# -*- coding: utf-8 -*-
"""codigo_original

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyzon2yPM_ZtmQWB1I0-cHZvP9ZC-Voh
"""

import time

def es_primo(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

inicio = time.time()

primos = []
for num in range(1, 100001):
    if es_primo(num):
        primos.append(num)

fin = time.time()
print(f"Tiempo de ejecución código original: {fin - inicio:.2f} segundos")