# -*- coding: utf-8 -*-
"""codigo_optimizado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0edAXtAhXX837BKDzjrAEMA1OxPmLwy
"""

import time
import numpy as np

def es_primo_optimizado(n):
    if n < 2:
        return False
    limite = int(n**0.5) + 1
    for i in range(2, limite):
        if n % i == 0:
            return False
    return True

inicio = time.time()

nums = np.arange(1, 100001)
primos = [num for num in nums if es_primo_optimizado(num)]

fin = time.time()
print(f"Tiempo de ejecución código optimizado: {fin - inicio:.2f} segundos")