# -*- coding: utf-8 -*-
"""código original vs el optimizado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cN-p-IDxah0iKPDNT629eHflxhi2RbYw
"""

import matplotlib.pyplot as plt

# Datos
codigos = ['Original', 'Optimizado']
tiempos = [53.473, 0.585]

# Crear la gráfica
plt.bar(codigos, tiempos, color=['red', 'green'])

# Añadir título y etiquetas
plt.title('Comparación de Tiempos de Ejecución')
plt.ylabel('Tiempo (segundos)')
plt.xlabel('Versión del Código')

# Mostrar valores encima de cada barra
for i, v in enumerate(tiempos):
    plt.text(i, v + 1, f"{v:.3f}", ha='center')

# Mostrar gráfica
plt.show()