# -*- coding: utf-8 -*-
"""medicion_tiempos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfTgjWgN_i9rAg367-xIZuZ1dc7xPMy2
"""

import time

# Medir tiempo del código original
start = time.time()
exec(open("codigo_original.py").read())
end = time.time()
print(f"Tiempo código original: {end - start:.2f} segundos")

# Medir tiempo del código optimizado
start = time.time()
exec(open("codigo_optimizado.py").read())
end = time.time()
print(f"Tiempo código optimizado: {end - start:.2f} segundos")